update sorting | responsiveness fixes
corona-school/web-user-app pull request #146
Opened 2021-03-12 22:16 UTC by waqas-mumtaz

2021-03-14 02:40 UTC, lsc0498 requested changes
There is still a slight problem at some screen widths:
<img width="570" alt="Bildschirmfoto 2021-03-14 um 03 35 18" src="https://user-images.githubusercontent.com/33378936/111055508-c4eff680-8476-11eb-8d6e-aff1ff3c2fde.png">
The overall design looks nice though 👍🎉

2021-03-14 02:40 UTC, lsc0498 commented on .gitignore
> +yarn.lock
We better don't "gitignore" `yarn.lock` and `.gitignore` 😉

2021-03-14 02:40 UTC, lsc0498 commented on src/components/course/SortParticipant.tsx
There are again many linter errors in this file. Please make sure you have merged `master` into this branch.

2021-03-14 02:40 UTC, lsc0498 commented on yarn.lock
Was updating `yarn.lock`on purpose?

2021-03-14 02:40 UTC, lsc0498 commented on src/components/course/SortParticipant.tsx
> +                Note
Here "grade" should be translated with "Klasse" instead of "Note".

2021-03-14 02:41 UTC, lsc0498 commented
And please make sure to resolve merge conflicts 😉

2021-03-17 14:50 UTC, waqas-mumtaz commented
> There is still a slight problem at some screen widths:
> <img alt="Bildschirmfoto 2021-03-14 um 03 35 18" width="570" src="https://user-images.githubusercontent.com/33378936/111055508-c4eff680-8476-11eb-8d6e-aff1ff3c2fde.png">
> The overall design looks nice though 👍🎉

@lsc0498 can you please mention the screen size?

2021-03-17 14:54 UTC, lsc0498 commented
> > There is still a slight problem at some screen widths:
> 
> > <img alt="Bildschirmfoto 2021-03-14 um 03 35 18" width="570" src="https://user-images.githubusercontent.com/33378936/111055508-c4eff680-8476-11eb-8d6e-aff1ff3c2fde.png">
> 
> > The overall design looks nice though 👍🎉
> 
> 
> 
> @lsc0498 can you please mention the screen size?

Just try different screen widths in the responsive mode of your browser. E.g. in Google Chrome you can change the width continuously in the development mode.

2021-03-23 18:39 UTC, lsc0498 approved these changes
Looks good now. Thank you!🙂

2021-03-23 18:39 UTC, merged