Filter for free courses + guest limit message updated
corona-school/web-user-app pull request #189
Opened 2021-06-13 20:20 UTC by realmayus

Closes https://github.com/corona-school/project-user/issues/250
Frontend part of https://github.com/corona-school/project-user/issues/333

2021-06-15 12:48 UTC, Jonasdoubleyou requested changes

2021-06-15 12:48 UTC, Jonasdoubleyou commented on src/components/course/CourseHeader.tsx
> +        if (c.subcourse.maxParticipants === 7) {
Please remove debug logging

2021-06-15 12:48 UTC, Jonasdoubleyou commented on src/components/course/CourseHeader.tsx
> +        return c.subcourse.participants < c.subcourse.maxParticipants;
How does `onlyFree` toggle this logic?

2021-06-19 21:37 UTC, realmayus commented
> How does onlyFree toggle this logic?

 @Jonasdoubleyou Hmm, seems like I forgot to add the check, sorry about that. I just pushed a commit to fix this - thanks for the review!

2021-06-19 23:16 UTC, Jonasdoubleyou approved these changes

2021-06-20 19:01 UTC, merged